# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class DarkFactory < Formula
  desc "CLI that orchestrates autonomous AI agents to implement GitHub issues"
  homepage "https://github.com/peter-stratton/dark-factory"
  version "0.1.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/peter-stratton/dark-factory/releases/download/v0.1.0/dark-factory_0.1.0_darwin_amd64.tar.gz"
      sha256 "07db64971d9d11369a115e7071b59e79a507b8101d435093906caae8dd1b453e"

      define_method(:install) do
        bin.install "godark"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/peter-stratton/dark-factory/releases/download/v0.1.0/dark-factory_0.1.0_darwin_arm64.tar.gz"
      sha256 "e9201f9cfbca400a0aac45961208d5f943dead2a787d2ef7f7acabdbb9bdafba"

      define_method(:install) do
        bin.install "godark"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/peter-stratton/dark-factory/releases/download/v0.1.0/dark-factory_0.1.0_linux_amd64.tar.gz"
      sha256 "62c53f3a98df4638374ff8b1fa7a063fdffdd8ed45d889d6781fc99a6bae1bdb"
      define_method(:install) do
        bin.install "godark"
      end
    end
  end
end
