# This file was generated by GoReleaser. DO NOT EDIT.
cask "godark" do
  name "godark"
  desc "CLI that orchestrates autonomous AI agents to implement GitHub issues"
  homepage "https://github.com/peter-stratton/dark-factory"
  version "0.6.1-rc1"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "godark"

  on_macos do
    on_intel do
      url "https://github.com/peter-stratton/dark-factory/releases/download/v#{version}/dark-factory_#{version}_darwin_amd64.tar.gz"
      sha256 "4a5257fed8f245c817d94336638b4c4b3e1ca56662ef192c5f6ced2ed57f020a"
    end
    on_arm do
      url "https://github.com/peter-stratton/dark-factory/releases/download/v#{version}/dark-factory_#{version}_darwin_arm64.tar.gz"
      sha256 "21d590bcfc9415f04d0c5e1b3006844e24cb1df1877946f289a3d5099c386ceb"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/peter-stratton/dark-factory/releases/download/v#{version}/dark-factory_#{version}_linux_amd64.tar.gz"
      sha256 "1060a03d6221b88c0b82a637fb568dd34dd493a1aff4043def268842e4269290"
    end
  end

  # No zap stanza required
end
